spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: default
server:
  port: 8080
aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: LTAI5tR63tGWE8SFnqKtCGEQ
    access-key-secret: TnD44Rkhocf6svy3FOkCQDUaQVJ0Gx
    bucket-name: wwhyiyun