spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: default
server:
  port: 8080

aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-nanjing.aliyuncs.com}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_SECRET:}
    bucket-name: ${ALIYUN_BUCKET_NAME:}

alipay:
  app-id: ${ALIPAY_APP_ID:2021000147682493}
  private-key: ${ALIPAY_PRIVATE_KEY:MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCM1hKDfShfC3DzB7OP8SPjHb1dXz9PLRMLaqwuXA2LfsX+8mGNQjeapHoTHRe+TeZr3ZJEYsy9nMZY4wWJu7eSGjps/0uFYfS7IZ/2A3OI3+ERcJ2GBd5SHhywY30/u/lMpeBCH7rMjbsnIoJbbLWGNliz9P7l5keormE3HAGl4ZO5dJcYsq0EDkcOksZUwB78AWG7INpxbnyoeSM3n/Zm+ajPKzScenzulLtua6AP6MXShbgN7Zhk9lPIQoa1qO4hStkoyjWERVDEzZAdoKXjKqCgXDkG2t4DK+9at68aG/MU31d4cIsKJ0FIkrFKvdb73J3jCyA9nn8carnMMc/lAgMBAAECggEAP5ZwKXoa/j7WMoSpqDYCNAs7cqsMlJ0PWjpBn3TkkLUehGu/a94X6PSWQYcDL2NQxCb4YXQSaRId5AgsefGNgqPg+VGTMZf2vX8DEDqisYwTvKISHW8M4BrEbUeeR2aBuv+x72kQGEdt1s+X99tvYjereSUG6Zo9hIWnUxCMFe6/3GCwoUcJivXEYkLWblU8IA5qPijfGMUtJZ+vTazNA4Yq9cdQSO41q2dZeEjjsUMnCWTg/oJsJomAfEHUhtbX3lGgGsa8x+K6AcjFi53XE7U9tJT2j4k1mGLQPh0vMks5UBmg/X0r55RYRJRIEx2hg190Hp0CCN3iAjMzF8gZgQKBgQD4re91jXdKab8y106UKhq+wqNEqgKA6xQ2by8iDRqztmWClXhU0zyOI5buvW5CzCp41FQKrm7Y45+5d6QgKGvTCr5tx12OVWHxbHn93heBeva/I4LQX7WIjxsThLT0BDmTd1QFV4Mg6jOWqauFn+yssqgi9SmjsphScfMivi4YVQKBgQCQ+2xg+jwJHGZf6rlZfItvO2ecQd6B7kXf50PWLF7/TvqP+4+O0pTS8C8xRxdjcMawsF2As5xZGNAhl80YUYOBlPPNVIa7lAMSnlQG5xHvUy009adtbJx9ooEDJASoTH1GToepETb5t5O9Oxxsir1UkO96yku44VU5lzLDp1ypUQKBgE6hIJ/4tQlQWmZG8c+jaIV8oYcqglQlAGUdzrdjkVfVik8516xqhjEjS6v9NYnlaGCAMnqWIPJvNqe8DqckYMOAGCo56XkBwlBFzmTY/nGwYaiaH9inCo09QoBva4/kbhgUmPp/azTTGLDAwT0lDf6lFsjG3/2kkMkwwoHvxD9pAoGAaaT7nVLaKl1qb9wvQXjSdbQY1LDevVjty7DOKqNcebeINyC8w/rIfUiNat/9t/U2owtwpta6R+Yfy0q9JUpIhEUQvn8oSkkZUBjU6862r+ixGVUjskWhZp7iWXKGfkh2RKP2kIi9wYs2eX44QRN70MJn7ta4BLkVjAiT8iPjDnECgYB2gCzEPi4xb4rpfnLjDgW1DsPnV5m6kThCLxUiEm0YUPlx5Na3wcdkMrho2TYw2AvUH+ONVBzYhhfsOdZfWKu70wrmDgRjSM2Ojxwag1NwBBz/NSzFsOaprU1z5jD0Bqv+M7Eg5+4Jymrq6yOTEhvZbHUtDhR5/7dceNa2Wpsi6Q==}
  alipay-public-key: ${ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoJzW09vaDtMXDT0d0TJPyP7li6X6M7BZqHjRrhA2cxC73FjmUn8QOj9O5RbOcvdWgoYCzFi6JB94cThYgucCnimCsqW3W05mEXAQcTnsXL9Oy/zLGw6uL2CJ8PNhJiwZ1NrOyMqfideqVx7xQTzbZBdPWWz5foGB0W8btY+nA4S/6SsSJCaeS5z+n6Xm4/X88KY0h8TtSoZ+kKaMS0OTMryi779YWEyAcabtl+Sys0dyH8YFxtyFQKB2cEotyy9Z2LHhFvyYA3pTHZNBES2zOK5R5dmQl/eSly3niHiNHALUnraP7av1WHR8xikrvNTU02zizOdtbqBpz1XWBo4JCQIDAQAB}
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: utf-8
  sign-type: RSA2
  notify-url:  http://kxhusi.natappfree.cc/alipay/notify
  return-url:  http://kxhusi.natappfree.cc/alipay/returnUrl
